---
version: '3.3'
services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=${POSTGRES_DBNAME}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - postgres-db
networks:
  postgres-db:
    name: postgres-db
    driver: bridge
