---
version: '3.3'
services:
  mysql:
    image: mysql:9
    container_name: mysql-db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - mysql-db
networks:
  mysql-db:
    name: mysql-db
    driver: bridge
